# -*- coding: utf-8 -*-
"""WSDL_Problem_1 Type 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uabVa9WlSv73C6LFueQuZmJlGxWDcAEq
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the function
def f(x):
    return x**4 - 3*x**3 + 2

# Generate x values
x_values = np.linspace(-2, 4, 400) # From -2 to 4 with 400 points

# Calculate y values
y_values = f(x_values)

# Plot the function
plt.figure(figsize=(10, 6))
plt.plot(x_values, y_values, label='f(x) = x^4 - 3x^3 + 2')
plt.title('Graph of f(x) = x^4 - 3x^3 + 2')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.5) # Add x-axis
plt.axvline(0, color='black', linewidth=0.5) # Add y-axis
plt.legend()
plt.show()

import sympy
import numpy as np
import matplotlib.pyplot as plt

# Define the symbolic variable
x_sym = sympy.symbols('x')

# Define the function symbolically
f_sym = x_sym**4 - 3*x_sym**3 + 2

# Calculate the derivative
f_prime_sym = sympy.diff(f_sym, x_sym)

print(f"The original function f(x) = {f_sym}")
print(f"The derivative f'(x) = {f_prime_sym}")

# Convert symbolic expressions to numerical functions for plotting
f_numerical = sympy.lambdify(x_sym, f_sym, 'numpy')
f_prime_numerical = sympy.lambdify(x_sym, f_prime_sym, 'numpy')

# Generate x values (reusing the range from the previous plot)
x_values = np.linspace(-2, 4, 400)

# Calculate y values for both the function and its derivative
y_values = f_numerical(x_values)
y_prime_values = f_prime_numerical(x_values)

# Plot both functions
plt.figure(figsize=(10, 6))
plt.plot(x_values, y_values, label='f(x) = x^4 - 3x^3 + 2', color='blue')
plt.plot(x_values, y_prime_values, label="f'(x) = 4x^3 - 9x^2", color='red', linestyle='--')
plt.title('Graph of f(x) and its Derivative f\'(x)')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.legend()
plt.show()

"""## Define Function and Derivative
Re-define the function f(x) = x^4 - 3x^3 + 2 and its derivative f'(x) = 4x^3 - 9x^2, preferably using SymPy for symbolic definition and then `lambdify` for numerical evaluation, similar to previous steps.

SymPy is a python library that is used here to work upon the function algebraically, with no numerical manipulations and approximations. It essentially focuses on the abstract and visible algebraic manipulation of any algebraic expression, ignoring any link between the symbols and values.

'lambdify' then converts the finished algebraic expression back into a function with the symbols as variables, linked to numbers in the underlying system's memory.

## Set Gradient Descent Parameters
Choose an initial starting point (x_initial), a learning rate, and the number of iterations for the gradient descent algorithm.

**Reasoning**:
The subtask requires defining the initial starting point, learning rate, and number of iterations for the gradient descent algorithm. I will use a code block to declare and initialize these variables.
"""

x_initial = 3.5  # Example: within the range of x_values [-2, 4]
learning_rate = 0.01  # Small positive value
num_iterations = 200  # Number of steps for gradient descent

print(f"Initial x: {x_initial}")
print(f"Learning rate: {learning_rate}")
print(f"Number of iterations: {num_iterations}")

"""## Implement Gradient Descent
Run the gradient descent algorithm. In each iteration, calculate the gradient at the current x-value, then update x by subtracting the learning rate multiplied by the gradient. Store the history of x-values and corresponding f(x) values.

**Reasoning**:
I will implement the gradient descent algorithm according to the instructions, including initializing history lists, iterating to update x using the gradient and learning rate, and storing the history of x and f(x) values.
"""

import sympy
import numpy as np

# Redefine symbolic variables and functions (as per previous cells for clarity)
x_sym = sympy.symbols('x')
f_sym = x_sym**4 - 3*x_sym**3 + 2
f_prime_sym = sympy.diff(f_sym, x_sym)

f_numerical = sympy.lambdify(x_sym, f_sym, 'numpy')
f_prime_numerical = sympy.lambdify(x_sym, f_prime_sym, 'numpy')

# Initialize history lists
x_history = []
f_x_history = []

# Initial values
x_current = x_initial # x_initial is from previous step

x_history.append(x_current)
f_x_history.append(f_numerical(x_current))

# Gradient Descent Loop
for i in range(num_iterations): # num_iterations is from previous step
    gradient = f_prime_numerical(x_current)
    x_current = x_current - learning_rate * gradient # learning_rate is from previous step
    x_history.append(x_current)
    f_x_history.append(f_numerical(x_current))

print(f"Gradient descent completed. Final x: {x_history[-1]:.4f}, Final f(x): {f_x_history[-1]:.4f}")
print(f"Number of iterations: {len(x_history)-1}")

"""## Visualize Gradient Descent
Plot the original function f(x) and superimpose the path taken by the gradient descent algorithm, showing how x and f(x) change over iterations. This will visualize the convergence towards a minimum.

**Reasoning**:
The subtask requires visualizing the gradient descent path on the function's plot. I will use `matplotlib.pyplot` to plot the original function `f(x)` and superimpose the gradient descent steps using the stored `x_history` and `f_x_history` variables, adhering to all specified plotting instructions.
"""

import matplotlib.pyplot as plt

# Plot the function and the gradient descent path
plt.figure(figsize=(10, 6))
plt.plot(x_values, y_values, label='f(x) = x^4 - 3x^3 + 2', color='blue', alpha=0.7)
plt.plot(x_history, f_x_history, 'o-', color='red', markersize=4, label='Gradient Descent Path')

plt.title('Gradient Descent Path on f(x)')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.legend()
plt.show()

"""## Report Minimum
Display the final x-value found by gradient descent and the corresponding minimum value of the function f(x) at that point.

**Reasoning**:
The subtask requires displaying the final x-value and corresponding f(x) value. I will print the last elements of the `x_history` and `f_x_history` lists, formatted as specified, with appropriate labels.
"""

print(f"Optimal x-value: {x_history[-1]:.4f}")
print(f"Minimum f(x) value: {f_x_history[-1]:.4f}")

"""## Summary:

### Data Analysis Key Findings
*   The function `f(x) = x^4 - 3x^3 + 2` and its derivative `f'(x) = 4x^3 - 9x^2` were correctly defined for the optimization.
*   Gradient descent parameters were set as follows: an initial starting point (`x_initial`) of 3.5, a `learning_rate` of 0.01, and `num_iterations` set to 200.
*   After 200 iterations of the gradient descent algorithm, the optimal x-value found was approximately 2.2500.
*   At this optimal x-value, the minimum function value `f(x)` was approximately -6.5430.
*   A visualization was generated, illustrating the path taken by the gradient descent algorithm from the initial point to the determined minimum on the function's curve.

### Insights or Next Steps
*   The gradient descent successfully converged to a local minimum of the function. To ensure this is a global minimum, different initial `x` values could be tested.
*   Further analysis could involve exploring the impact of varying the `learning_rate` and `num_iterations` on the convergence speed and the accuracy of the found minimum.

"""